apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-report-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/inConsciousness/Brest_Cancer_Grading_and_Report_Generation  # 🔄 Replace with your GitHub repo
    targetRevision: HEAD
    path: deployments/k8s/llm-report
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
